name: shop_manager
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/drawer_header_img.jpg
    - assets/images/callbox.png
    - assets/images/cecaw.jpeg
    - assets/images/drawer_header_img.jpg
    - assets/images/friandises.jpeg
    - assets/images/mtn.jpeg
    - assets/images/nina.png
    - assets/images/orange.png
    - assets/images/remede.png
    - assets/images/reserve.jpeg
    - assets/images/smobilpay.png